<a href="https://colab.research.google.com/github/sindhu123-wq/git-python-project/blob/main/50_Startups_MLR_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Step 1
#import data from csv file
import pandas as pd
data=pd.read_csv('50_Startups_MLR.csv')

In [ ]:
data

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [ ]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [ ]:
#Step 2
#Separate both input and output variables
#Independent Variables

X=data.iloc[:,0:-1].values

In [ ]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [ ]:
#Dependent Variables

Y=data.iloc[:,-1].values

In [ ]:
Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [ ]:
#Step3-Missing values

#Missing values in X

from sklearn.impute import SimpleImputer
import numpy as np

imputer=SimpleImputer(missing_values=0.0,strategy='mean')
imputer.fit(X[:,0:3])  #identification
X[:,0:3]=imputer.transform(X[:,0:3])

In [ ]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [ ]:
#Step4-Coverting string datatype to int

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X=ct.fit_transform(X)

In [ ]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [ ]:
#Step 5:Feature scaling
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X[:,0:3]=sc.fit_transform(X[:,0:3])

In [ ]:
X

array([[-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        2.065353823535753, 0.5607529145307771, 471784.1],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        2.0011816540097396, 1.0828065830760836, 443898.53],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        1.7876353785627508, -0.7282570276886139, 407934.54],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        1.5761202694773906, -0.09636463069766295, 383199.62],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        1.5232929185676003, -1.0799193536742695, 366168.42],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        1.284692326161382, -0.7762390705391548, 362861.36],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        1.3485627010758503, 0.9321472084702611, 127716.82],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        1.24787128

In [ ]:
#Step6 : Splitting the data into train and test

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
X_train

array([[1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        -0.7082443080012771, 1.3105352482185189, 210797.67],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        -1.1225077891910298, 0.2059246909295515, 201126.82],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        1.020344968417513, 0.9869521013922136, 311613.29],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        1.3485627010758503, 0.9321472084702611, 127716.82],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        0.005846055879263835, -0.7954691674668046, 140574.81],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        0.3544813368166687, 0.5101789529969049, 252664.93],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        2.065353823535753, 0.5607529145307771, 471784.1],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        3.39388686

In [ ]:
X_test

array([[-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        0.5858577498622899, -0.3875990892467969, 229160.95],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        -0.7178543906664394, -1.3086575295015461, 205517.64],
       [-0.7177405625652736, -0.6859943405700356, 1.3932610920384718,
        -1.7783795469527552, -2.5094088368614424, 224494.78489361703],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        -0.4967576525037133, -0.6593240327322979, 214634.81],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        2.0011816540097396, 1.0828065830760836, 443898.53],
       [-0.7177405625652736, 1.4577379737113254, -0.7177405625652735,
        -0.2505275337238643, 2.210140504801784, 118148.2],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
        -0.8917363647252757, -1.3831215613922057, 174999.3],
       [1.3932610920384723, -0.6859943405700356, -0.7177405625652735,
    