<a href="https://colab.research.google.com/github/sindhu123-wq/git-python-project/blob/main/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#DATA-PREPROCESSING
#step-1 : we have to import data from csv file
import pandas as pd
data=pd.read_csv('Data.csv')



In [ ]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data.columns #to view column names

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
data['Country'] #to view the data of a specified column

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: object

In [ ]:
data['Country'][0] #extracting data
data['Age'][6]

nan

In [ ]:
data.head(3)#extracting specified no. of rows

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [ ]:
data.head()#absence of argument leads to the extraction of first 5 rows

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
data.tail(3)#extracting data from bottom to top

Country   Age   Salary Purchased
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data.tail()#absence of argument leads to the extraction of last 5 rows

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#step-2 : we have to separate both input{independent} & output{dependent} variables
#Y=f(X)
#X-INDEPENDENT VARIABLES : {'Country','Age','Salary'}
X=data.iloc[:,0:-1].values#First Slice is for rows & second for columns


In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
 #Dependent variable : Y
 Y=data.iloc[:,-1].values

In [ ]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
#step-3 : we talk about handling of missing data 
#if missing data is in categorical column we go under frequency technique and if it is of numerical, we go with mean method
#missing data is denoted with NAN
!pip install sklearn #sk(scientific computing kit) is ued to handle missing data

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')#identifying missing values
imputer.fit(X[:,1:3])#getting data of 1st & 2nd coulmns
X[:,1:3]=imputer.transform(X[:,1:3])#substitutes the mean


In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#step-4 : Taking care of string data by converting string data into numerical data
#indeppendent variable at index 0
from sklearn.compose import ColumnTransformer#we use this module since categorical data exists in column
from sklearn.preprocessing import OneHotEncoder#conversion from categorical data into numerical data
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
#setting remainder="passthrough" means that all the columns which are included in the transformers list can be passed without any transformation
X=ct.fit_transform(X)

In [ ]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [ ]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step-5 : Feature scaling
from sklearn.preprocessing import StandardScaler #standardscaler makes the values in one scale
sc=StandardScaler()
X[:,3:5]=sc.fit_transform(X[:,3:5])

In [ ]:
X

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [ ]:
#step-6:splitting data into train and test
from sklearn.model_selection import train_test_split#we will be getting xtrain,xtest,ytrain,ytest
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)


In [ ]:
X_train

array([[0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16]],
      dtype=object)

In [ ]:
Y_test

array([0, 0])

In [ ]:
X_test

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921]],
      dtype=object)

In [ ]:
Y_train

array([1, 0, 1, 0, 0, 1, 1, 1])