<a href="https://colab.research.google.com/github/sindhu123-wq/git-python-project/blob/main/Salary_Prediction_SLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.read_csv('Salary_Data_SLR.csv')

In [ ]:
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
X=data.iloc[:,0:1].values
X=X.reshape(-1,1)

In [ ]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
Y=data.iloc[:,-1].values
Y=Y.reshape(-1,1)

In [ ]:
Y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 93940.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
X_train

array([[ 3.2],
       [ 3. ],
       [ 4.5],
       [ 2. ],
       [ 5.9],
       [ 5.3],
       [ 5.1],
       [ 8.7],
       [ 7.1],
       [ 4. ],
       [ 8.2],
       [ 4.1],
       [ 1.3],
       [ 1.1],
       [ 3.2],
       [10.3],
       [ 4. ],
       [ 6. ],
       [ 7.9],
       [ 9. ],
       [ 1.5],
       [ 3.9],
       [ 9.6],
       [ 3.7]])

In [ ]:
Y_test

array([[ 91738.],
       [121872.],
       [ 39891.],
       [ 67938.],
       [116969.],
       [ 56642.]])

In [ ]:
X_test

array([[ 6.8],
       [10.5],
       [ 2.2],
       [ 4.9],
       [ 9.5],
       [ 2.9]])

In [ ]:
Y_train

array([[ 54445.],
       [ 60150.],
       [ 61111.],
       [ 43525.],
       [ 81363.],
       [ 83088.],
       [ 66029.],
       [109431.],
       [ 98273.],
       [ 55794.],
       [113812.],
       [ 57081.],
       [ 46205.],
       [ 39343.],
       [ 64445.],
       [122391.],
       [ 56957.],
       [ 93940.],
       [101302.],
       [105582.],
       [ 37731.],
       [ 63218.],
       [112635.],
       [ 57189.]])

In [ ]:
#Y=f(X)=aX+b
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
regressor.coef_


array([[9421.92027886]])

In [ ]:
regressor.intercept_

array([26246.35724217])

In [ ]:
regressor.predict(X_test)

array([[ 90315.4151384 ],
       [125176.52017017],
       [ 46974.58185566],
       [ 72413.76660857],
       [115754.59989132],
       [ 53569.92605086]])

In [ ]:
regressor.predict(Y_test)

array([[8.64374369e+08],
       [1.14829451e+09],
       [3.75876068e+08],
       [6.40132666e+08],
       [1.10209884e+09],
       [5.33702655e+08]])

In [ ]:
Y_test

array([[ 91738.],
       [121872.],
       [ 39891.],
       [ 67938.],
       [116969.],
       [ 56642.]])